version: '3.8'

services:
  vless-generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vless-generator
    ports:
      - "8080:8080"
    environment:
      - LOG_LEVEL=info
      - LOG_FORMAT=json
    command: [
      "-port", "8080",
      "-log-level", "${LOG_LEVEL:-info}",
      "-log-format", "${LOG_FORMAT:-json}"
    ]
    restart: unless-stopped
    volumes:
      # Optional: mount custom templates if you modify embedded assets during development
      # - ./templates:/templates:ro
      # Optional: mount logs directory
      # - ./logs:/var/log:rw
